services:
    Gigamarr\SyliusBankOfGeorgiaPlugin\Client\BankOfGeorgiaClient:
        arguments:
            - '@sylius.http_client'
            - '@Gigamarr\SyliusBankOfGeorgiaPlugin\Provider\GatewayConfigProvider'
            - '%gigamarr.sylius_bank_of_georgia_plugin.api_base_url%'
            - '@monolog.logger.bank_of_georgia'
