services:
    Gigamarr\SyliusBankOfGeorgiaPlugin\Controller\PaymentStatusChangeCallbackController:
        tags: [controller.service_arguments]
        arguments:
            - '@sylius.repository.order'
