services:
    Gigamarr\SyliusBankOfGeorgiaPlugin\Controller\HelloWorldController:
        arguments:
            - '@Gigamarr\SyliusBankOfGeorgiaPlugin\Client\BankOfGeorgiaClient'
        tags:
            - name: 'controller.service_arguments'
