services:
    Gigamarr\SyliusBankOfGeorgiaPlugin\Form\Type\BankOfGeorgiaGatewayConfigurationType:
        tags:
            - name: sylius.gateway_configuration_type
              type: bank_of_georgia
              label: Bank of Georgia
            - name: form.type