services:
    Gigamarr\SyliusBankOfGeorgiaPlugin\Payum\Factory\BankOfGeorgiaGatewayFactory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            - Gigamarr\SyliusBankOfGeorgiaPlugin\Payum\Factory\BankOfGeorgiaGatewayFactory
        tags:
            - name: payum.gateway_factory_builder
              factory: bank_of_georgia

    Gigamarr\SyliusBankOfGeorgiaPlugin\Payum\Action\AuthorizeAction:
        public: true
        arguments:
            - '@Gigamarr\SyliusBankOfGeorgiaPlugin\Client\BankOfGeorgiaClient'
            - '@Gigamarr\SyliusBankOfGeorgiaPlugin\Formatter\OrderToAuthorizeActionPayloadFormatter'
            - '@monolog.logger.bank_of_georgia'
        tags:
            - { name: payum.action, factory: '%gigamarr.sylius_bank_of_georgia_plugin.gateway_factory_name%', alias: payum.action.authorize }

    Gigamarr\SyliusBankOfGeorgiaPlugin\Payum\Action\CaptureAction:
        public: true
        arguments:
            - '@Gigamarr\SyliusBankOfGeorgiaPlugin\Client\BankOfGeorgiaClient'
            - '@monolog.logger.bank_of_georgia'
        tags:
            - { name: payum.action, factory: '%gigamarr.sylius_bank_of_georgia_plugin.gateway_factory_name%', alias: payum.action.capture }

    Gigamarr\SyliusBankOfGeorgiaPlugin\Payum\Action\RefundAction:
        public: true
        arguments:
            - '@Gigamarr\SyliusBankOfGeorgiaPlugin\Client\BankOfGeorgiaClient'
            - '@monolog.logger.bank_of_georgia'
        tags:
            - { name: payum.action, factory: '%gigamarr.sylius_bank_of_georgia_plugin.gateway_factory_name%', alias: payum.action.refund }

    Gigamarr\SyliusBankOfGeorgiaPlugin\Payum\Action\UnblockPreAuthAction:
        public: true
        arguments:
            - '@Gigamarr\SyliusBankOfGeorgiaPlugin\Client\BankOfGeorgiaClient'
            - '@monolog.logger.bank_of_georgia'
        tags:
            - { name: payum.action, factory: '%gigamarr.sylius_bank_of_georgia_plugin.gateway_factory_name%', alias: payum.action.unblock }
