services:
    gigamarr.sylius_bank_of_georgia_plugin.processor.authorization:
        class: Gigamarr\SyliusBankOfGeorgiaPlugin\Resolver\AuthorizationProcessor
        public: true
        arguments:
            - '@payum'
