services:
    gigamarr.sylius_bank_of_georgia_plugin.processor.authorization:
        class: Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\AuthorizationProcessor
        public: true
        arguments:
            - '@payum'
            - '@gigamarr.sylius_bank_of_georgia_plugin.client.bank_of_georgia'
