services:
    Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\AuthorizationProcessor:
        public: true
        arguments:
            - '@payum'
            - '%gigamarr.sylius_bank_of_georgia_plugin.gateway_factory_name%'

    Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\CaptureProcessor:
        public: true
        arguments:
            - '@payum'
            - '%gigamarr.sylius_bank_of_georgia_plugin.gateway_factory_name%'

    Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\RefundProcessor:
        public: true
        arguments:
            - '@payum'
            - '%gigamarr.sylius_bank_of_georgia_plugin.gateway_factory_name%'

    Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\PreAuthUnblockProcessor:
        public: true
        arguments:
            - '@payum'
            - '%gigamarr.sylius_bank_of_georgia_plugin.gateway_factory_name%'
