services:
    Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\AuthorizationProcessor:
        public: true
        arguments:
            - '@payum'
            - '@Gigamarr\SyliusBankOfGeorgiaPlugin\Client\BankOfGeorgiaClient'
