services:
    Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\AuthorizationProcessor:
        class: Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\AuthorizationProcessor
        public: true
        arguments:
            - '@payum'
            - '@Gigamarr\SyliusBankOfGeorgiaPlugin\Client\BankOfGeorgiaClient'
            - '@monolog.logger.bank_of_georgia'
