services:
    Gigamarr\SyliusBankOfGeorgiaPlugin\Provider\GatewayConfigProvider:
        arguments:
            - '@sylius.repository.gateway_config'
            - '%gigamarr_sylius_bank_of_georgia_plugin.gateway_factory_name%'
