services:
    Gigamarr\SyliusBankOfGeorgiaPlugin\Resolver\GatewayConfigResolver:
        arguments:
            - '@sylius.repository.gateway_config'
            - '%gigamarr.sylius_bank_of_georgia_plugin.gateway_factory_name%'
