winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                authorize_bank_of_georgia_order:
                    on: ['complete']
                    do: ['@Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\AuthorizationProcessor', 'process']
                    args: ['object']
    
    sylius_payment:
        callbacks:
            guard:  
                guard_complete:
                    on: 'complete'
                    do: ['@Gigamarr\SyliusBankOfGeorgiaPlugin\StateMachine\Guard\GuardPaymentComplete', '__invoke']
                    args: ['object']
            before:
                payment_complete:
                    on: ['complete']
                    do: ['@Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\CaptureProcessor', 'process']
                    args: ['object']
                payment_cancel:
                    on: ['cancel']
                    do: ['@Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\CaptureProcessor', 'process']
                    args: ['object']

sylius_resource:
    resources:
        gigamarr_sylius_bank_of_georgia_plugin.status_change_callback:
            classes:
                model: Gigamarr\SyliusBankOfGeorgiaPlugin\Entity\StatusChangeCallback

monolog:
    channels:
        - bank_of_georgia
    handlers:
        bank_of_georgia:
            type: stream
            path: "%kernel.logs_dir%/bank_of_georgia.log"
            level: debug
            channels: [ bank_of_georgia ]
