winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                authorize_bank_of_georgia_order:
                    on: ['complete']
                    do: ['@Gigamarr\SyliusBankOfGeorgiaPlugin\Processor\AuthorizationProcessor', 'process']
                    args: ['object']

monolog:
    channels:
        - bank_of_georgia
    handlers:
        bank_of_georgia:
            type: stream
            path: "%kernel.logs_dir%/bank_of_georgia.log"
            level: debug
            channels: [ bank_of_georgia ]
