winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                authorize_bank_of_georgia_order:
                    on: ['complete']
                    do: ['@gigamarr.sylius_bank_of_georgia_plugin.processor.authorization', 'resolve']
                    args: ['object']
