imports:
    - { resource: "@GigamarrSyliusBankOfGeorgiaPlugin/Resources/config/services/form_types.yaml" }
    - { resource: "@GigamarrSyliusBankOfGeorgiaPlugin/Resources/config/services/payum.yaml" }
    - { resource: "@GigamarrSyliusBankOfGeorgiaPlugin/Resources/config/services/resolvers.yaml" }
