imports:
    - { resource: "services/client.yaml" }
    - { resource: "services/controllers.yaml" }
    - { resource: "services/form_types.yaml" }
    - { resource: "services/formatters.yaml" }
    - { resource: "services/payum.yaml" }
    - { resource: "services/processors.yaml" }
    - { resource: "services/providers.yaml" }
    - { resource: "services/state_machine_guards.yaml" }
