app.sylius_payment:
    class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
    arguments: [ Gigamarr\SyliusBankOfGeorgiaPlugin\Payum\SyliusPaymentGatewayFactory ]
    tags:
      - { name: payum.gateway_factory_builder, factory: sylius_payment }

Gigamarr\SyliusBankOfGeorgiaPlugin\Form\Type\SyliusGatewayConfigurationType:
    tags:
      - { name: sylius.gateway_configuration_type, type: sylius_payment, label: 'Sylius Payment' }
      - { name: form.type }